name: Déploiement Portfolio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull
        working-directory: /home/amelien/work/portfolio
        run: |
          git pull https://x-access-token:${{ secrets.PULL }}@github.com/amcpqb86/portfolio.git

      - name: Build image
        working-directory: /home/amelien/work/portfolio/
        run: docker build . -t portfolio

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Lancer Docker Compose
        run: docker compose -f /srv/portfolio/docker-compose.yml up -d
