name: Déploiement Portfolio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull
        working-directory: /home/amelien/work/portfolio
        run: |
          git pull https://x-access-token:${{ secrets.PULL }}@github.com/amcpqb86/layro-front.git

      - name: Build image
        working-directory: /home/amelien/work/layro/front
        run: docker build . -t layro-front

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Lancer Docker Compose
        run: docker compose -f /srv/layro-front/docker-compose.yml up -d
      - name: LogSnag - Notify deployment
        run: |
          curl -X POST https://api.logsnag.com/v1/log \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.LOGSNAG_TOKEN }}" \
            -d '{
              "project": "layro",
              "channel": "deploy",
              "event": "Front deployed",
              "description": "Nouvelle version du front déployé en production",
              "icon": "🚀",
              "notify": true
            }'
